// <auto-generated />
using System;
using KartTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KartTrack.Api.Migrations
{
    [DbContext(typeof(KartTrackDbContext))]
    [Migration("20261008211644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KartTrack.Api.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageLap")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FastestLap")
                        .HasColumnType("REAL");

                    b.Property<int>("KartNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLaps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageLap = 61.200000000000003,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "Antonio",
                            FastestLap = 58.450000000000003,
                            KartNumber = 7,
                            Notes = "First test session at TeamSport Edmonton",
                            Position = 3,
                            TotalLaps = 12,
                            TrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageLap = 65.400000000000006,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverName = "Adam",
                            FastestLap = 62.100000000000001,
                            KartNumber = 14,
                            Notes = "Outdoor session at Daytona Milton Keynes",
                            Position = 6,
                            TotalLaps = 10,
                            TrackId = 2
                        });
                });

            modelBuilder.Entity("KartTrack.Api.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsIndoor = true,
                            Location = "London",
                            Name = "TeamSport Edmonton"
                        },
                        new
                        {
                            Id = 2,
                            IsIndoor = false,
                            Location = "Milton Keynes",
                            Name = "Daytona Milton Keynes"
                        });
                });

            modelBuilder.Entity("KartTrack.Api.Models.Session", b =>
                {
                    b.HasOne("KartTrack.Api.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
